### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by bbday** [vulnersCom/burp-vulners-scanner#10]
Sep 01, 2018 4:44:42 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: vulnersSession=YV5C4G8V9U5J3NUFO86RIGPNT2ZUVYCP00LC3YN9OPZYZ7S60TL2TVNWZMAIR459BUVC1S8PQZK62XHIYHYMRRRD306U99NCW0P951J5R0CD6S4MEE833F877J6D3OS3:8UhRTZbJHiHdLZoF7j8oUMf9tuw; Domain=.vulners.com; expires=Sat, 01 Sep 2018 14:44:52 GMT; HttpOnly; Max-Age=10; Path=/; Secure". Invalid 'expires' attribute: Sat, 01 Sep 2018 14:44:52 GMT
Sep 01, 2018 4:44:43 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: vulnersSession=BLLNIX9BV3XJNFQKRWW691GYS629ASOC22TQ5AO0LRADDTGEYG8C15I5U5H8H6VK61GYYANGKWPIN1PBKSVMCBNUF6Y5PNLP9OJF4L1FBR23BZ7WV7IZNZYHFFQV56IQ:Wg16vwdvh5JSOHmkDccL054Elv8; Domain=.vulners.com; expires=Sat, 01 Sep 2018 14:44:53 GMT; HttpOnly; Max-Age=10; Path=/; Secure". Invalid 'expires' attribute: Sat, 01 Sep 2018 14:44:53 GMT
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.mashape.unirest.http.exceptions.UnirestException: java.lang.IllegalArgumentException: Invalid offsets: the list should be in sequence and offsets should not overlap.
	at com.mashape.unirest.http.HttpClientHelper$1.failed(HttpClientHelper.java:86)
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:154)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:278)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:123)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:164)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:339)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:317)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:278)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid offsets: the list should be in sequence and offsets should not overlap.
	at burp.v0d.addScanIssue(Unknown Source)
	at burp.nb.addScanIssue(Unknown Source)
	at burp.aph.addScanIssue(Unknown Source)
	at burp.VulnersService$1.onScannerSuccess(VulnersService.java:89)
	at burp.VulnersRestCallback.onSuccess(VulnersRestCallback.java:42)
	at burp.VulnersRestCallback.completed(VulnersRestCallback.java:60)
	at com.mashape.unirest.http.HttpClientHelper$1.completed(HttpClientHelper.java:82)
	at com.mashape.unirest.http.HttpClientHelper$1.completed(HttpClientHelper.java:75)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:432)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:325)
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:267)
	... 10 more

**Comment by vankyver** [comment]
Overlap Issue finally fixed in 1.2
