### ISSUE TITLE
 java.net.UnknownHostException

### ISSUE THREAD

**Issue by Hipapheralkus** [vulnersCom/burp-vulners-scanner#6]
When I open Burp from CMD, and load the newest version of Extender from official BApp store, I can see following exception in CMD window:
```
C:\Program Files\BurpSuitePro>java -jar burpsuite_pro.jar
com.mashape.unirest.http.exceptions.UnirestException: java.net.UnknownHostException: vulners.com
        at com.mashape.unirest.http.HttpClientHelper$1.failed(HttpClientHelper.java:86)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:419)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionRequestFailed(AbstractClientExchangeHandler.java:335)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$100(AbstractClientExchangeHandler.java:62)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.failed(AbstractClientExchangeHandler.java:378)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalPoolEntryCallback.failed(PoolingNHttpClientConnectionManager.java:503)
        at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:134)
        at org.apache.http.nio.pool.AbstractNIOConnPool.fireCallbacks(AbstractNIOConnPool.java:453)
        at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:285)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:265)
        at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:363)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:125)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:74)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:107)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:91)
        at com.mashape.unirest.http.HttpClientHelper.requestAsync(HttpClientHelper.java:102)
        at com.mashape.unirest.request.BaseRequest.asJsonAsync(BaseRequest.java:76)
        at burp.VulnersService.loadRules(VulnersService.java:165)
        at burp.BurpExtender.initPassiveScan(BurpExtender.java:32)
        at com.codemagi.burp.PassiveScan.initialize(PassiveScan.java:37)
        at com.codemagi.burp.BaseExtender.registerExtenderCallbacks(BaseExtender.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at burp.mch.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: vulners.com
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(Unknown Source)
        at java.net.InetAddress.getAddressesFromNameService(Unknown Source)
        at java.net.InetAddress.getAllByName0(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at java.net.InetAddress.getAllByName(Unknown Source)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:608)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:579)
        at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:426)
        at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:275)
        ... 19 more
```

Is it possible you gracefully reported to user (in my case, I'm behind firewall and I need properly set proxy to load the database) that the URL is unreachable, instead throwing this exception?
Thanks

**Comment by Hipapheralkus** [comment]
Also, when I properly edit and enable proxy in both User settings - upstream proxy to vulners.com; as well as enable and set proxy in the extender as such, after the 1st click I can also see this exceptions:
```
java.lang.IllegalThreadStateException
        at java.lang.Thread.start(Unknown Source)
        at com.mashape.unirest.http.HttpClientHelper.requestAsync(HttpClientHelper.java:99
        at com.mashape.unirest.request.BaseRequest.asJsonAsync(BaseRequest.java:76)
        at burp.VulnersService.loadRules(VulnersService.java:165)
        at burp.gui.TabComponent$3$1.run(TabComponent.java:93)
        at java.lang.Thread.run(Unknown Source)
```
On the second Load, it works
